### ISSUE TITLE
Can Balena Basics™ Station work with AS923 frequency plan

### ISSUE THREAD

**Issue by jjopittaya** [mpous/basicstation#33]
Hello, I am a beginner at LoRaWAN. I wonder that whether Balena Basics™ Station can work with AS923-925 (“AS2”) Frequency plan? If so how can I configure it?

I have read in the Readme.md file that
"If your region is not EU you can set it using TTN_REGION. At the moment there is only one server available is eu1."
Does this mean that I can set the TTN_REGION value to AS923 and be ready to go?

Thank you very much

**Comment by carlrakwireless** [comment]
Hi @mpous , for IN865. Can I use `eu1` or `au1`?

**Comment by carlrakwireless** [comment]
> Hi @mpous , for IN865. Can I use `eu1` or `au1`?

It tried it. IN865 is working on au1 👍🏽
