### ISSUE TITLE
GW disconnects and reconnects

### ISSUE THREAD

**Issue by wolfm123** [mpous/basicstation#38]
Dear Marc,

my GW (RPiI 4 RAK 2287) disconnects and reconnects:
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/10433343/131200947-42300ad3-bdeb-44c5-afa8-20d8a6f6e910.png">

The reason might be that the WS connection is shutting down and opening up. Enclosed I send a copy of the summary-entry of Balena-Cloud..
[basicstation_wispy-paper-28.08.21_02_56_58_(+0200).txt](https://github.com/mpous/basicstation/files/7069904/basicstation_wispy-paper-28.08.21_02_56_58_.%2B0200.txt)

Thank you for any help!

Kind regards

Manfred
-------------------------------------------
Manfred Wolf, Dillingen, Germany
mwolf@bndlg.de
+49 171 33 44 636
https://linkedin.com/in/mwolf123
-------------------------------------------

**Comment by mpous** [comment]
Hello @wolfm123 could you please confirm if your LoRa concentrator is SPI or USB?

**Comment by wolfm123** [comment]
Dear Marc,

Thank you for your response.

My LoRa - concentrator is a USB-version. I found out, that I should have a SPI-version. So I will order this SPI kind and I will try your Balena offers again.

Moreover I plan to buy a  mPCIe to USB converter board <https://store.rakwireless.com/collections/accessories/products/mpcie-to-usb-board> for the already bought USB-version.

Is your Balena script working for this combination with the a Raspberry Pi 3+ as well ?

Thank you and kind regards

Manfred
 -------------------------------------------
Manfred Wolf
Hölderlinstr. 21
89407 Dillingen a. d. Donau
***@***.***
+49 171 33 44 636
https://linkedin.com/in/mwolf123

**Comment by mpous** [comment]
@wolfm123 balena basicstation project works on Pi3 (32 and 64 bits) and Pi4 but at the moment on SPI-versions.

We also have the [balenaFin](https://www.balena.io/fin/) which has a USB mPCIE and I can't run the basicstation if i'm not using the SPi version with a hat. Looking forward to get contributions here :)

Let me know when you get the SPI LoRa concentrator!
