### ISSUE TITLE
Works fine with RHF0M301 / SEEED LoRa/LoRaWAN Gateway Kit

### ISSUE THREAD

**Issue by rgot-org** [mpous/basicstation#44]
Works with [SEEED LoRa/LoRaWAN Gateway Kit](https://wiki.seeedstudio.com/LoRa_LoRaWan_Gateway_Kit/)

- Raspberry PI 3
- Gateway module RHF0M301–868
- PRI 2 Bridge RHF4T002 (reset: GPIO7 / header pin 26)

1. Go to balenaCloud dashboard and get into your LoRa gateway device site.

2. Click **Device Variables** button on the left menu and set 

- ```GW_RESET_GPIO``` to ```7```
- ```GW_RESET_PIN``` to ```26```
![image](https://user-images.githubusercontent.com/31351194/146678789-23cdfb4a-ad8b-49bd-a7fa-a0471808dc3a.png)

3. Click **Device Configuration**  button on the left menu and set
- ```Define DT overlays``` to ```"spi0-1cs"```
![image](https://user-images.githubusercontent.com/31351194/146678739-bd1124aa-4650-4156-8a5f-020f17a8445e.png)

Then the Sx1301 reset correctly !

**Comment by mpous** [comment]
Thank you for this @rgot-org could you please add a PR on the `README.md` so everyone with the same LoRa concentrator can use it?
